name: Auto-Tag Release

on:
  push:
    branches: [main]

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <-- Add this to allow writing tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Auto Tag
        uses: Klemensas/action-autotag@stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

